# Generated by Django 4.2.7 on 2025-08-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            # Fix foreign key constraints to point to correct tables
            """
            -- Disable foreign key checks temporarily
            PRAGMA foreign_keys = OFF;
            
            -- Drop the old table
            DROP TABLE IF EXISTS inventory_stockmovement_old;
            
            -- Rename current table to old
            ALTER TABLE inventory_stockmovement RENAME TO inventory_stockmovement_old;
            
            -- Create new table with correct foreign keys
            CREATE TABLE inventory_stockmovement (
                id char(32) NOT NULL PRIMARY KEY,
                movement_type varchar(20) NOT NULL,
                quantity integer NOT NULL,
                previous_stock integer NOT NULL,
                new_stock integer NOT NULL,
                unit_cost decimal NULL,
                reference_number varchar(100) NULL,
                notes text NULL,
                created_at datetime NOT NULL,
                created_by_id integer NULL REFERENCES auth_user(id),
                product_id char(32) NOT NULL REFERENCES products_product(id),
                supplier_id char(32) NULL REFERENCES suppliers_supplier(id)
            );
            
            -- Copy data from old table
            INSERT INTO inventory_stockmovement 
            SELECT * FROM inventory_stockmovement_old;
            
            -- Drop old table
            DROP TABLE inventory_stockmovement_old;
            
            -- Re-enable foreign key checks
            PRAGMA foreign_keys = ON;
            """,
            reverse_sql="-- This migration cannot be reversed"
        ),
    ]
